service: curso-sls

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
useDotenv: true

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  profile: default

functions:
  getAllPersonas:
    handler: src/controller/personas.getAllPersonas
    events:
      - http:
          path: personas/get-all
          method: get
  getPersona:
    handler: src/controller/personas.getPersona
    events:
      - http:
          path: personas/get-person/{cedula}
          method: get
  addPersona:
    handler: src/controller/personas.addPersona
    events:
      - http:
          path: personas/add-person
          method: post
  deletePersona:
    handler: src/controller/personas.deletePersona
    events:
      - http:
          path: personas/delete-person/{cedula}
          method: delete
  editPersona:
    handler: src/controller/personas.editPersona
    events:
      - http:
          path: personas/edit-person/{cedula}
          method: put